"""Initial migration

Revision ID: 80b9d4476a6c
Revises: 
Create Date: 2024-02-17 21:48:20.207502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b9d4476a6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'view_lists', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'watch_lists', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watch_lists', type_='foreignkey')
    op.drop_constraint(None, 'view_lists', type_='foreignkey')
    # ### end Alembic commands ###
