"""change name.string -> name.json genre 2

Revision ID: 812b41637215
Revises: 1d15dc5d0f12
Create Date: 2024-02-18 21:01:41.585467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812b41637215'
down_revision: Union[str, None] = '1d15dc5d0f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'genre_movie', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre_movie', type_='foreignkey')
    op.drop_table('genres')
    # ### end Alembic commands ###
